version: '3'

services:
  multisigwallet:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile
    image: multisigwallet
    container_name: multisigwallet
    privileged: true
    stdin_open: true
    network_mode: "host"
    tty: true
    ports:
      - "127.0.0.1:8282:8282/tcp"
    # volumes:
    #   - ..:/home/user/multisigwallet:rw

